#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ARTIFACT_PATH=""

usage() {
    echo "Usage: $0 [--artifact PATH]" >&2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --artifact)
            if [[ $# -lt 2 ]]; then
                usage
                exit 2
            fi
            ARTIFACT_PATH="$2"
            shift 2
            ;;
        *)
            usage
            exit 2
            ;;
    esac
done

cd "$PROJECT_DIR"

failed=0

report_failure() {
    echo "Public boundary check failed: $1" >&2
    failed=1
}

ignored_tracked="$(git ls-files -ci --exclude-standard)"
if [[ -n "$ignored_tracked" ]]; then
    report_failure "ignored files are still tracked"
    printf '%s\n' "$ignored_tracked" >&2
fi

for forbidden_pathspec in \
    AGENTS.md \
    '.agents/**' \
    '.codex/**' \
    '.local/**' \
    'docs/agent-journals/**' \
    'docs/superpowers/**' \
    'docs/assets/gif-storyboard/**' \
    docs/assets/hantoggle-storyboard-core-v1.png; do
    matches="$(git ls-files -- "$forbidden_pathspec")"
    if [[ -n "$matches" ]]; then
        report_failure "local-only paths are tracked"
        printf '%s\n' "$matches" >&2
    fi
done

private_path_files="$(
    git grep -I -l -E \
        '(/Users/|/home/|[A-Za-z]:\\Users\\|file://|\.codex/generated_images)' \
        -- . ':!Scripts/check-public-boundary.sh' || true
)"
if [[ -n "$private_path_files" ]]; then
    report_failure "tracked text contains a local or personal path"
    printf '%s\n' "$private_path_files" >&2
fi

ai_attribution_files="$(
    git grep -I -i -l -E \
        '(Tester:.*(Codex|ChatGPT|Claude)|Co-authored-by:.*(Codex|ChatGPT|Claude)|generated by (Codex|ChatGPT|Claude))' \
        -- . ':!Scripts/check-public-boundary.sh' || true
)"
if [[ -n "$ai_attribution_files" ]]; then
    report_failure "tracked text contains AI process attribution"
    printf '%s\n' "$ai_attribution_files" >&2
fi

secret_marker_files="$(
    git grep -I -l -E \
        '(-----BEGIN ([A-Z0-9 ]+ )?PRIVATE KEY-----|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}|github_pat_[A-Za-z0-9_]{20,}|gh[pousr]_[A-Za-z0-9]{20,}|xox[baprs]-[A-Za-z0-9-]{10,}|sk_live_[A-Za-z0-9]{12,}|rk_live_[A-Za-z0-9]{12,}|AIza[0-9A-Za-z_-]{30,}|https?://[^[:space:]/]+:[^[:space:]@]+@)' \
        -- . ':!Scripts/check-public-boundary.sh' || true
)"
if [[ -n "$secret_marker_files" ]]; then
    report_failure "tracked text contains a credential marker"
    printf '%s\n' "$secret_marker_files" >&2
fi

credential_named_files="$(
    git ls-files | grep -E -i \
        '(^|/)(\.env($|\.)|\.netrc$|[^/]*\.(p12|pfx|keychain|keychain-db|developerprofile|mobileprovision|provisionprofile)$|[^/]*(credential|secret|token)[^/]*\.json$)' || true
)"
if [[ -n "$credential_named_files" ]]; then
    report_failure "credential-like filenames are tracked"
    printf '%s\n' "$credential_named_files" >&2
fi

if [[ -n "$ARTIFACT_PATH" ]]; then
    if [[ ! -e "$ARTIFACT_PATH" ]]; then
        report_failure "artifact does not exist: $ARTIFACT_PATH"
    else
        artifact_marker_found=0
        while IFS= read -r -d '' artifact_file; do
            if strings -a "$artifact_file" | grep -E -q \
                '(/Users/|/home/|[A-Za-z]:\\Users\\|/private/var/folders/|\.codex/generated_images|-----BEGIN ([A-Z0-9 ]+ )?PRIVATE KEY-----|AKIA[0-9A-Z]{16}|github_pat_|gh[pousr]_|xox[baprs]-|sk_live_)'; then
                echo "Artifact contains a forbidden path or credential marker: ${artifact_file#"$PROJECT_DIR"/}" >&2
                artifact_marker_found=1
            fi
        done < <(find "$ARTIFACT_PATH" -type f -print0)

        if [[ "$artifact_marker_found" == "1" ]]; then
            failed=1
        fi
    fi
fi

if [[ "$failed" == "1" ]]; then
    exit 1
fi

echo "Public boundary check passed."
